# -*- coding: utf-8 -*-
"""Bank Marketing Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14I9tw31ig8S_IJClZQbP3VPvunvRaVZK
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("bank-full.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

df.head()

df.info()

df.describe()

print("Numerical Features:")
print(df.select_dtypes(include=np.number).columns)

print("\nCategorical Features:")
print(df.select_dtypes(include='object').columns)

data_array = df.to_numpy()

print(data_array.shape)

data_array[:5]

data_array[:10, :5]

numeric_df = df.select_dtypes(include=np.number)

arr = numeric_df.to_numpy()

print("Mean:")
print(np.mean(arr, axis=0))

print("Median:")
print(np.median(arr, axis=0))

print("Max:")
print(np.max(arr, axis=0))

print("Min:")
print(np.min(arr, axis=0))

high_balance = arr[arr[:,1] > 5000]

print(high_balance.shape)

df.head()

df.duplicated().sum()

df.sort_values("balance", ascending=False).head()

df[df["housing"]=="yes"].head()

df.groupby("job")["balance"].mean().sort_values(ascending=False)

df["y"].value_counts()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["age"], bins=30)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["balance"], bins=40)
plt.title("Balance Distribution")
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["campaign"], bins=20)
plt.title("Campaign Contacts")
plt.show()

import seaborn as sns

sns.countplot(x="y", data=df)
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    x="education",
    hue="y",
    data=df
)

plt.show()

plt.figure(figsize=(10,6))

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x=df["balance"]
)

plt.show()

missing = df.isnull().sum()

missing_percent = (
    missing/len(df)
)*100

pd.DataFrame({
    "Missing":missing,
    "Percent":missing_percent
})

from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include=np.number).columns

imputer = SimpleImputer(strategy="mean")

df[num_cols] = imputer.fit_transform(df[num_cols])

print("Imputation Complete")

print(df.isnull().sum().sum())

binary_cols = [
    "default",
    "housing",
    "loan",
    "y"
]

for col in binary_cols:
    df[col] = df[col].map({
        "yes":1,
        "no":0
    })

nominal_cols = [
    "job",
    "marital",
    "contact",
    "month",
    "poutcome"
]

df = pd.get_dummies(
    df,
    columns=nominal_cols,
    drop_first=True
)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["education"] = le.fit_transform(
    df["education"]
)

Q1 = df["balance"].quantile(0.25)
Q3 = df["balance"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

print(lower, upper)

outliers = df[
    (df["balance"] < lower) |
    (df["balance"] > upper)
]

print(outliers.shape)

df["balance"] = np.where(
    df["balance"] > upper,
    upper,
    df["balance"]
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled = scaler.fit_transform(
    df.drop("y",axis=1)
)

scaled.shape

from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

scaled_minmax = mms.fit_transform(
    df.drop("y",axis=1)
)

scaled_minmax.shape

print("StandardScaler Mean:",
      scaled.mean())

print("MinMax Min:",
      scaled_minmax.min())

print("MinMax Max:",
      scaled_minmax.max())

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

X = pd.read_csv("bank-full.csv")

y = X["y"]

X = X.drop("y", axis=1)

numeric_features = X.select_dtypes(
    include=np.number
).columns

categorical_features = X.select_dtypes(
    include="object"
).columns

numeric_transformer = Pipeline([
    ("imputer",
     SimpleImputer(strategy="mean")),

    ("scaler",
     StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer",
     SimpleImputer(strategy="most_frequent")),

    ("onehot",
     OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    (
        "num",
        numeric_transformer,
        numeric_features
    ),
    (
        "cat",
        categorical_transformer,
        categorical_features
    )
])

X_processed = preprocessor.fit_transform(X)

print(X_processed.shape)

print("Original Shape:", X.shape)

print(
    "Processed Shape:",
    X_processed.shape
)

print(
    "Missing Values:",
    np.isnan(
        X_processed.toarray()
        if hasattr(X_processed,"toarray")
        else X_processed
    ).sum()
)

